name: Go
on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    name: Test with Go ${{ matrix.go_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.16]
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Set up Go ${{ matrix.go_version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run Unit Tests
      run: ./scripts/runUnitTests.sh
